services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx_proxy_manager_data:/data
      - letsencrypt:/etc/letsencrypt

  # portainer config from https://earthly.dev/blog/portainer-for-docker-container-management/
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - '9000:9000'
      - '9443:9443'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # filebrowser config from https://hub.docker.com/r/hurlenko/filebrowser
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
     - '8080:8080'
    volumes:
    #edit directory for these file
      - /DATA_DIR:/data
      - /CONFIG_DIR:/config 
    #in my usage, I'm mapping /home/user to /data and ./config to /config
    env_file:
      - .env
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped

volumes:
  nginx_proxy_manager_data:
  letsencrypt:
  portainer_data:
